version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=senha
      - DB_NAME=conecta_ifpe
      - JWT_SECRET=segredo
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: conecta_ifpe
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
